# AR parameters such as FFT parameters.
audio_repr: ar_msn.AR_MSN
weight_file: /Users/piotr/Documents/studia/mgr/MIR/msn-audio/msn-audio/model-epoch=470-train_loss=5.49.ckpt
feature_d: 3072
sample_rate: 16000
n_fft: 1024
window_size: 1024
hop_size: 160
n_mels: 64
f_min: 60
f_max: 7800
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 256
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Fine-tuning parameters.
## CAUTION: The following parameters not confirmed to work. ##
warmup_epochs: 5
mixup: 0.5
ft_bs: 256
ft_lr: 0.001
ft_early_stop_epochs: -1 # -1: no early stopping
ft_epochs: 200
ft_freq_mask: 30
ft_time_mask: 100
ft_rrc: True

# Unit duration in seconds for one audio segment.
unit_sec: 0.95
# BYOL parameters.
proj_size: 64
proj_dim: 4096
ema_decay: 0.99
